{actor_learning_rate: 1.0e-05, alpha_learning_rate: 0.0001, alpha_threshold: 10, batch_size: 256,
  conservative_weight: 5.0, critic_learning_rate: 3.0e-05, gamma: 1.0, initial_alpha: 1.0,
  initial_temperature: 1.0, tau: 0.005, temp_learning_rate: 0.0001}
