{actor_learning_rate: 1.0e-05, alpha_learning_rate: 0.0001, alpha_threshold: 5, batch_size: 256,
  conservative_weight: 5.0, critic_learning_rate: 0.03, gamma: 0.99, initial_alpha: 0.2,
  initial_temperature: 1.0, tau: 0.005, temp_learning_rate: 0.0001}
