batch_size: 256
gamma: [0.99, 1.0]
actor_learning_rate: [0.00001, 0.0001, 0.001, 0.01]
critic_learning_rate: [0.00003, 0.0003, 0.003, 0.03]
temp_learning_rate: 0.0001
alpha_learning_rate: 0.0001
tau: 0.005
initial_temperature: 1.0
initial_alpha: [0.2,0.5,1.0]
alpha_threshold: [5, 10]
conservative_weight: [5.0,1.0]